services:
  db:
    image: postgres:15
    container_name: cybin_postgres
    environment:
      POSTGRES_USER: cybinuser
      POSTGRES_PASSWORD: cybinpassword
      POSTGRES_DB: cybindb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"